# .github/workflows/deploy.yml
name: Deploy with Ansible

on:
  workflow_dispatch:  # manually trigger from GitHub
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python and Ansible
        run: |
          ansible-galaxy collection install azure.azcollection
          $ pip install 'ansible[azure]'
          python -m pip install --upgrade pip
          # pip install ansible azure-cli

      - name: Run Ansible Playbook
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT: ${{ secrets.AZURE_TENANT_ID }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook ansible-test-azure.yml
          # inventory.ini
